"""empty message

Revision ID: 9a0a075d6dbb
Revises: bd087cc87b89
Create Date: 2018-05-05 00:54:04.583686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a0a075d6dbb'
down_revision = 'bd087cc87b89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tracks', ['filelocation'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tracks', type_='unique')
    # ### end Alembic commands ###
