"""empty message

Revision ID: d12994d5be66
Revises: aafe62b74b9c
Create Date: 2018-04-18 22:43:15.176763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd12994d5be66'
down_revision = 'aafe62b74b9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track_library',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist', sa.String(length=140), nullable=True),
    sa.Column('album', sa.String(length=140), nullable=True),
    sa.Column('track', sa.String(length=140), nullable=True),
    sa.Column('filelocation', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_log_timestamp'), 'request_log', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_log_timestamp'), table_name='request_log')
    op.drop_table('request_log')
    op.drop_table('track_library')
    # ### end Alembic commands ###
